# Generated by Django 3.0.6 on 2020-05-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='item',
        ),
    ]
